### ISSUE TITLE
Integrate 'Move' recipe into Production.py

### ISSUE THREAD

**Issue by eddiekelley** [metroeast/PatchBotProcessors#3]
It seems that the "Move.py" recipe can be moved into Production.py, which would allow it to use the normal AutoPkg schedule for running these recipes.

In this scenario, older (production-ready) versions of packages would be moved into production at the time that the main recipe for the product is run.

**Comment by elkram** [comment]
We're borrowing PatchManager.py:patch() to perform the lookup, and PatchBotTools/Move.py logic/math to perform the tests.
